import type { StickerData } from '../ui/Sticker';

export const mockStickers: StickerData[] = [
  {
    id: 'sticker-1',
    type: 'IMAGE',
    title: '바이닐 중독 💿',
    isNew: true,
    posX: 188.9,
    posY: 203.9,
    rotation: -12.95,
    scale: 1,
    badgeOffsetX: 45.17,
    badgeOffsetY: -39.78,
    image: {
      url: '/board/stickers/vinyl.png',
      width: 178,
      height: 177,
    },
  },
  {
    id: 'sticker-2',
    type: 'IMAGE',
    title: '동물 밈 짤줍 😻',
    isNew: true,
    posX: 105.35,
    posY: 315.35,
    rotation: 12.43,
    scale: 1,
    badgeOffsetX: -24.79,
    badgeOffsetY: 49.68,
    image: {
      url: '/board/stickers/cat.png',
      width: 185,
      height: 177,
    },
  },
  {
    id: 'sticker-4',
    type: 'IMAGE',
    title: '위에서 보면 🙄',
    isNew: true,
    posX: 248.69,
    posY: 459.56,
    rotation: 0,
    scale: 1,
    badgeOffsetX: 46,
    badgeOffsetY: 75,
    image: {
      url: '/board/stickers/girl.png',
      width: 152,
      height: 172,
    },
  },
  {
    id: 'sticker-5',
    type: 'IMAGE',
    title: '물멍 🌊',
    isNew: true,
    posX: 102.08,
    posY: 459.55,
    rotation: -17.76,
    scale: 1,
    badgeOffsetX: -30.42,
    badgeOffsetY: 42.49,
    image: {
      url: '/board/stickers/bench.png',
      width: 139,
      height: 95,
      offsetX: 1.48,
      offsetY: -6.21,
      rotation: 18.8,
      crop: { x: 0, y: 417, width: 736, height: 503 },
      cornerRadius: 8,
      borderWidth: 3,
      borderColor: 'white',
    },
  },
  {
    id: 'sticker-text',
    type: 'TEXT',
    title: '독서기록📚',
    isNew: true,
    posX: 263.23,
    posY: 320.21,
    rotation: 12.69,
    scale: 1,
    badgeOffsetX: 11.19,
    badgeOffsetY: -54.71,
    textContent:
      '흔히들 말한다. 상대가 원하는 걸 해주는 것이 사랑이라고. 하지만 그건 작은 사랑인지도 모른다. 상대가 싫어하는 걸 하지 않는 것이야말로 큰 사랑이 아닐까.',
    textBoxWidth: 129.13,
    textBoxHeight: 93.26,
  },
];
